package activitydiagram.activitydiagram.algebra.operation;

public interface ActivitydiagramActivitydiagramControlFlowOperation extends activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramActivityEdgeOperation {
}