package activitydiagram.activitydiagram.algebra.operation;

public interface ActivitydiagramActivitydiagramJoinNode_AspectOperation extends activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramJoinNodeOperation, activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramControlNode_AspectOperation {
	Boolean isReady();
}