package activitydiagram.activitydiagram.algebra.operation;

public interface ActivitydiagramActivitydiagramMergeNodeOperation extends activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramControlNodeOperation {
	Boolean hasOffers();
}