package activitydiagram.activitydiagram.algebra.operation;

public interface ActivitydiagramActivitydiagramBooleanVariable_AspectOperation extends activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramBooleanVariableOperation, activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramVariable_AspectOperation {
}