package activitydiagram.activitydiagram.algebra.operation;

public interface ActivitydiagramActivitydiagramVariable_AspectOperation extends activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramVariableOperation {
}