package activitydiagram.activitydiagram.algebra.operation;

public interface ActivitydiagramActivitydiagramInputOperation extends activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramInputOperation {
}