package activitydiagram.activitydiagram.algebra.operation;

public interface ActivitydiagramActivitydiagramExecutableNodeOperation extends activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramActivityNodeOperation {
}