package activitydiagram.activitydiagram.algebra.operation;

public interface ActivitydiagramActivitydiagramBooleanBinaryExpression_AspectOperation extends activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramBooleanBinaryExpressionOperation, activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramBooleanExpression_AspectOperation {
	void execute();
}