package activitydiagram.activitydiagram.algebra.operation;

public interface ActivitydiagramActivitydiagramTrace_AspectOperation extends activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramTraceOperation {
}