package activitydiagram.activitydiagram.algebra.operation;

public interface ActivitydiagramActivitydiagramBooleanVariableOperation extends activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramVariableOperation {
}