package activitydiagram.activitydiagram.algebra.operation;

public interface ActivitydiagramActivitydiagramFinalNode_AspectOperation extends activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramFinalNodeOperation, activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramControlNode_AspectOperation {
}