package activitydiagram.activitydiagram.algebra.operation;

public interface ActivitydiagramActivitydiagramOpaqueAction_AspectOperation extends activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramOpaqueActionOperation, activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramAction_AspectOperation {
	void execute();
	void doAction();
}