package activitydiagram.activitydiagram.algebra.operation;

public interface ActivitydiagramActivitydiagramControlFlow_AspectOperation extends activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramControlFlowOperation, activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramActivityEdge_AspectOperation {
}