package activitydiagram.activitydiagram.algebra.operation;

public interface ActivitydiagramActivitydiagramJoinNodeOperation extends activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramControlNodeOperation {
	Boolean isReady();
}