package activitydiagram.activitydiagram.algebra.operation;

public interface ActivitydiagramActivitydiagramBooleanBinaryExpressionOperation extends activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramBooleanExpressionOperation {
	void execute();
}