package activitydiagram.activitydiagram.algebra.operation;

public interface ActivitydiagramActivitydiagramIntegerCalculationExpression_AspectOperation extends activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramIntegerCalculationExpressionOperation, activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramIntegerExpression_AspectOperation {
	void execute();
}