package activitydiagram.activitydiagram.algebra.operation;

public interface ActivitydiagramActivitydiagramMergeNode_AspectOperation extends activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramMergeNodeOperation, activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramControlNode_AspectOperation {
	Boolean hasOffers();
}