package activitydiagram.activitydiagram.algebra.operation;

public interface ActivitydiagramActivitydiagramIntegerVariable_AspectOperation extends activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramIntegerVariableOperation, activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramVariable_AspectOperation {
}