package activitydiagram.activitydiagram.algebra.operation;

public interface ActivitydiagramActivitydiagramExpression_AspectOperation extends activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramExpressionOperation {
	void execute();
}