package activitydiagram.activitydiagram.algebra.operation;

public interface ActivitydiagramActivitydiagramIntegerVariableOperation extends activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramVariableOperation {
}