package activitydiagram.activitydiagram.algebra.operation;

public interface ActivitydiagramActivitydiagramIntegerComparisonExpressionOperation extends activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramIntegerExpressionOperation {
	void execute();
}