package activitydiagram.activitydiagram.algebra.operation;

public interface ActivitydiagramActivitydiagramBooleanUnaryExpressionOperation extends activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramBooleanExpressionOperation {
	void execute();
}