package activitydiagram.algebra.impl;

public interface ActivitydiagramAlgebraImpl extends activitydiagram.algebra.ActivitydiagramAlgebra
	<activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramActionOperation,activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramAction_AspectOperation,activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramActivityOperation,activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramActivityEdgeOperation,activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramActivityEdge_AspectOperation,activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramActivityFinalNodeOperation,activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramActivityFinalNode_AspectOperation,activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramActivityNodeOperation,activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramActivityNode_AspectOperation,activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramActivity_AspectOperation,activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramBooleanBinaryExpressionOperation,activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramBooleanBinaryExpression_AspectOperation,activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramBooleanExpressionOperation,activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramBooleanExpression_AspectOperation,activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramBooleanUnaryExpressionOperation,activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramBooleanUnaryExpression_AspectOperation,activitydiagram.$default.algebra.operation.Activitydiagram$defaultBooleanValueOperation,activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramBooleanVariableOperation,activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramBooleanVariable_AspectOperation,activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramControlFlowOperation,activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramControlFlow_AspectOperation,activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramControlNodeOperation,activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramControlNode_AspectOperation,activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramControlTokenOperation,activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramControlToken_AspectOperation,activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramDecisionNodeOperation,activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramDecisionNode_AspectOperation,activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramExecutableNodeOperation,activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramExecutableNode_AspectOperation,activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramExpressionOperation,activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramExpression_AspectOperation,activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramFinalNodeOperation,activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramFinalNode_AspectOperation,activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramForkNodeOperation,activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramForkNode_AspectOperation,activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramForkedTokenOperation,activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramForkedToken_AspectOperation,activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramInitialNodeOperation,activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramInitialNode_AspectOperation,activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramInputOperation,activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramInputOperation,activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramInputValueOperation,activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramInputValueOperation,activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramIntegerCalculationExpressionOperation,activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramIntegerCalculationExpression_AspectOperation,activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramIntegerComparisonExpressionOperation,activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramIntegerComparisonExpression_AspectOperation,activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramIntegerExpressionOperation,activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramIntegerExpression_AspectOperation,activitydiagram.$default.algebra.operation.Activitydiagram$defaultIntegerValueOperation,activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramIntegerVariableOperation,activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramIntegerVariable_AspectOperation,activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramJoinNodeOperation,activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramJoinNode_AspectOperation,activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramMergeNodeOperation,activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramMergeNode_AspectOperation,activitydiagram.$default.algebra.operation.Activitydiagram$defaultNamedElementOperation,activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramOfferOperation,activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramOffer_AspectOperation,activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramOpaqueActionOperation,activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramOpaqueAction_AspectOperation,activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramTokenOperation,activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramToken_AspectOperation,activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramTraceOperation,activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramTrace_AspectOperation,activitydiagram.$default.algebra.operation.Activitydiagram$defaultValueOperation,activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramVariableOperation,activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramVariable_AspectOperation> {
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramAction_AspectOperation action_Aspect(final activitydiagram.Action_Aspect action_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramAction_AspectOperation(action_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramAction_AspectOperation namedElement_action_Aspect(final activitydiagram.Action_Aspect action_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramAction_AspectOperation(action_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramAction_AspectOperation activityNode_action_Aspect(final activitydiagram.Action_Aspect action_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramAction_AspectOperation(action_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramAction_AspectOperation executableNode_Aspect_action_Aspect(final activitydiagram.Action_Aspect action_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramAction_AspectOperation(action_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramAction_AspectOperation activityNode_Aspect_action_Aspect(final activitydiagram.Action_Aspect action_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramAction_AspectOperation(action_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramAction_AspectOperation action_action_Aspect(final activitydiagram.Action_Aspect action_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramAction_AspectOperation(action_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramAction_AspectOperation executableNode_action_Aspect(final activitydiagram.Action_Aspect action_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramAction_AspectOperation(action_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramActivityOperation activity(final activitydiagram.Activity activity) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramActivityOperation(activity, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramActivityOperation namedElement_activity(final activitydiagram.Activity activity) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramActivityOperation(activity, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramActivityEdge_AspectOperation activityEdge_Aspect(final activitydiagram.ActivityEdge_Aspect activityEdge_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramActivityEdge_AspectOperation(activityEdge_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramActivityEdge_AspectOperation activityEdge_activityEdge_Aspect(final activitydiagram.ActivityEdge_Aspect activityEdge_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramActivityEdge_AspectOperation(activityEdge_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramActivityEdge_AspectOperation namedElement_activityEdge_Aspect(final activitydiagram.ActivityEdge_Aspect activityEdge_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramActivityEdge_AspectOperation(activityEdge_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramActivityFinalNodeOperation activityFinalNode(final activitydiagram.ActivityFinalNode activityFinalNode) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramActivityFinalNodeOperation(activityFinalNode, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramActivityFinalNodeOperation controlNode_activityFinalNode(final activitydiagram.ActivityFinalNode activityFinalNode) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramActivityFinalNodeOperation(activityFinalNode, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramActivityFinalNodeOperation namedElement_activityFinalNode(final activitydiagram.ActivityFinalNode activityFinalNode) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramActivityFinalNodeOperation(activityFinalNode, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramActivityFinalNodeOperation finalNode_activityFinalNode(final activitydiagram.ActivityFinalNode activityFinalNode) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramActivityFinalNodeOperation(activityFinalNode, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramActivityFinalNodeOperation activityNode_activityFinalNode(final activitydiagram.ActivityFinalNode activityFinalNode) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramActivityFinalNodeOperation(activityFinalNode, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramActivityFinalNode_AspectOperation activityFinalNode_Aspect(final activitydiagram.ActivityFinalNode_Aspect activityFinalNode_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramActivityFinalNode_AspectOperation(activityFinalNode_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramActivityFinalNode_AspectOperation namedElement_activityFinalNode_Aspect(final activitydiagram.ActivityFinalNode_Aspect activityFinalNode_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramActivityFinalNode_AspectOperation(activityFinalNode_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramActivityFinalNode_AspectOperation activityNode_activityFinalNode_Aspect(final activitydiagram.ActivityFinalNode_Aspect activityFinalNode_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramActivityFinalNode_AspectOperation(activityFinalNode_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramActivityFinalNode_AspectOperation controlNode_Aspect_activityFinalNode_Aspect(final activitydiagram.ActivityFinalNode_Aspect activityFinalNode_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramActivityFinalNode_AspectOperation(activityFinalNode_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramActivityFinalNode_AspectOperation controlNode_activityFinalNode_Aspect(final activitydiagram.ActivityFinalNode_Aspect activityFinalNode_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramActivityFinalNode_AspectOperation(activityFinalNode_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramActivityFinalNode_AspectOperation finalNode_activityFinalNode_Aspect(final activitydiagram.ActivityFinalNode_Aspect activityFinalNode_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramActivityFinalNode_AspectOperation(activityFinalNode_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramActivityFinalNode_AspectOperation activityFinalNode_activityFinalNode_Aspect(final activitydiagram.ActivityFinalNode_Aspect activityFinalNode_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramActivityFinalNode_AspectOperation(activityFinalNode_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramActivityFinalNode_AspectOperation activityNode_Aspect_activityFinalNode_Aspect(final activitydiagram.ActivityFinalNode_Aspect activityFinalNode_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramActivityFinalNode_AspectOperation(activityFinalNode_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramActivityFinalNode_AspectOperation finalNode_Aspect_activityFinalNode_Aspect(final activitydiagram.ActivityFinalNode_Aspect activityFinalNode_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramActivityFinalNode_AspectOperation(activityFinalNode_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramActivityNode_AspectOperation activityNode_Aspect(final activitydiagram.ActivityNode_Aspect activityNode_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramActivityNode_AspectOperation(activityNode_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramActivityNode_AspectOperation activityNode_activityNode_Aspect(final activitydiagram.ActivityNode_Aspect activityNode_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramActivityNode_AspectOperation(activityNode_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramActivityNode_AspectOperation namedElement_activityNode_Aspect(final activitydiagram.ActivityNode_Aspect activityNode_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramActivityNode_AspectOperation(activityNode_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramActivity_AspectOperation activity_Aspect(final activitydiagram.Activity_Aspect activity_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramActivity_AspectOperation(activity_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramActivity_AspectOperation namedElement_activity_Aspect(final activitydiagram.Activity_Aspect activity_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramActivity_AspectOperation(activity_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramActivity_AspectOperation activity_activity_Aspect(final activitydiagram.Activity_Aspect activity_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramActivity_AspectOperation(activity_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramBooleanBinaryExpressionOperation booleanBinaryExpression(final activitydiagram.BooleanBinaryExpression booleanBinaryExpression) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramBooleanBinaryExpressionOperation(booleanBinaryExpression, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramBooleanBinaryExpressionOperation booleanExpression_booleanBinaryExpression(final activitydiagram.BooleanBinaryExpression booleanBinaryExpression) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramBooleanBinaryExpressionOperation(booleanBinaryExpression, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramBooleanBinaryExpressionOperation expression_booleanBinaryExpression(final activitydiagram.BooleanBinaryExpression booleanBinaryExpression) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramBooleanBinaryExpressionOperation(booleanBinaryExpression, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramBooleanBinaryExpression_AspectOperation booleanBinaryExpression_Aspect(final activitydiagram.BooleanBinaryExpression_Aspect booleanBinaryExpression_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramBooleanBinaryExpression_AspectOperation(booleanBinaryExpression_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramBooleanBinaryExpression_AspectOperation expression_Aspect_booleanBinaryExpression_Aspect(final activitydiagram.BooleanBinaryExpression_Aspect booleanBinaryExpression_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramBooleanBinaryExpression_AspectOperation(booleanBinaryExpression_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramBooleanBinaryExpression_AspectOperation booleanBinaryExpression_booleanBinaryExpression_Aspect(final activitydiagram.BooleanBinaryExpression_Aspect booleanBinaryExpression_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramBooleanBinaryExpression_AspectOperation(booleanBinaryExpression_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramBooleanBinaryExpression_AspectOperation expression_booleanBinaryExpression_Aspect(final activitydiagram.BooleanBinaryExpression_Aspect booleanBinaryExpression_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramBooleanBinaryExpression_AspectOperation(booleanBinaryExpression_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramBooleanBinaryExpression_AspectOperation booleanExpression_booleanBinaryExpression_Aspect(final activitydiagram.BooleanBinaryExpression_Aspect booleanBinaryExpression_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramBooleanBinaryExpression_AspectOperation(booleanBinaryExpression_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramBooleanBinaryExpression_AspectOperation booleanExpression_Aspect_booleanBinaryExpression_Aspect(final activitydiagram.BooleanBinaryExpression_Aspect booleanBinaryExpression_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramBooleanBinaryExpression_AspectOperation(booleanBinaryExpression_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramBooleanExpression_AspectOperation booleanExpression_Aspect(final activitydiagram.BooleanExpression_Aspect booleanExpression_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramBooleanExpression_AspectOperation(booleanExpression_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramBooleanExpression_AspectOperation expression_Aspect_booleanExpression_Aspect(final activitydiagram.BooleanExpression_Aspect booleanExpression_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramBooleanExpression_AspectOperation(booleanExpression_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramBooleanExpression_AspectOperation booleanExpression_booleanExpression_Aspect(final activitydiagram.BooleanExpression_Aspect booleanExpression_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramBooleanExpression_AspectOperation(booleanExpression_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramBooleanExpression_AspectOperation expression_booleanExpression_Aspect(final activitydiagram.BooleanExpression_Aspect booleanExpression_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramBooleanExpression_AspectOperation(booleanExpression_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramBooleanUnaryExpressionOperation booleanUnaryExpression(final activitydiagram.BooleanUnaryExpression booleanUnaryExpression) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramBooleanUnaryExpressionOperation(booleanUnaryExpression, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramBooleanUnaryExpressionOperation booleanExpression_booleanUnaryExpression(final activitydiagram.BooleanUnaryExpression booleanUnaryExpression) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramBooleanUnaryExpressionOperation(booleanUnaryExpression, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramBooleanUnaryExpressionOperation expression_booleanUnaryExpression(final activitydiagram.BooleanUnaryExpression booleanUnaryExpression) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramBooleanUnaryExpressionOperation(booleanUnaryExpression, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramBooleanUnaryExpression_AspectOperation booleanUnaryExpression_Aspect(final activitydiagram.BooleanUnaryExpression_Aspect booleanUnaryExpression_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramBooleanUnaryExpression_AspectOperation(booleanUnaryExpression_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramBooleanUnaryExpression_AspectOperation expression_Aspect_booleanUnaryExpression_Aspect(final activitydiagram.BooleanUnaryExpression_Aspect booleanUnaryExpression_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramBooleanUnaryExpression_AspectOperation(booleanUnaryExpression_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramBooleanUnaryExpression_AspectOperation expression_booleanUnaryExpression_Aspect(final activitydiagram.BooleanUnaryExpression_Aspect booleanUnaryExpression_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramBooleanUnaryExpression_AspectOperation(booleanUnaryExpression_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramBooleanUnaryExpression_AspectOperation booleanUnaryExpression_booleanUnaryExpression_Aspect(final activitydiagram.BooleanUnaryExpression_Aspect booleanUnaryExpression_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramBooleanUnaryExpression_AspectOperation(booleanUnaryExpression_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramBooleanUnaryExpression_AspectOperation booleanExpression_booleanUnaryExpression_Aspect(final activitydiagram.BooleanUnaryExpression_Aspect booleanUnaryExpression_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramBooleanUnaryExpression_AspectOperation(booleanUnaryExpression_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramBooleanUnaryExpression_AspectOperation booleanExpression_Aspect_booleanUnaryExpression_Aspect(final activitydiagram.BooleanUnaryExpression_Aspect booleanUnaryExpression_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramBooleanUnaryExpression_AspectOperation(booleanUnaryExpression_Aspect, this);
	} 
	@Override
	default activitydiagram.$default.algebra.operation.Activitydiagram$defaultBooleanValueOperation booleanValue(final activitydiagram.BooleanValue booleanValue) {
		return new activitydiagram.$default.algebra.impl.operation.Activitydiagram$defaultBooleanValueOperation(booleanValue, this);
	} 
	@Override
	default activitydiagram.$default.algebra.operation.Activitydiagram$defaultBooleanValueOperation value_booleanValue(final activitydiagram.BooleanValue booleanValue) {
		return new activitydiagram.$default.algebra.impl.operation.Activitydiagram$defaultBooleanValueOperation(booleanValue, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramBooleanVariableOperation booleanVariable(final activitydiagram.BooleanVariable booleanVariable) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramBooleanVariableOperation(booleanVariable, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramBooleanVariableOperation variable_booleanVariable(final activitydiagram.BooleanVariable booleanVariable) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramBooleanVariableOperation(booleanVariable, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramBooleanVariable_AspectOperation booleanVariable_Aspect(final activitydiagram.BooleanVariable_Aspect booleanVariable_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramBooleanVariable_AspectOperation(booleanVariable_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramBooleanVariable_AspectOperation booleanVariable_booleanVariable_Aspect(final activitydiagram.BooleanVariable_Aspect booleanVariable_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramBooleanVariable_AspectOperation(booleanVariable_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramBooleanVariable_AspectOperation variable_Aspect_booleanVariable_Aspect(final activitydiagram.BooleanVariable_Aspect booleanVariable_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramBooleanVariable_AspectOperation(booleanVariable_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramBooleanVariable_AspectOperation variable_booleanVariable_Aspect(final activitydiagram.BooleanVariable_Aspect booleanVariable_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramBooleanVariable_AspectOperation(booleanVariable_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramControlFlowOperation controlFlow(final activitydiagram.ControlFlow controlFlow) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramControlFlowOperation(controlFlow, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramControlFlowOperation activityEdge_controlFlow(final activitydiagram.ControlFlow controlFlow) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramControlFlowOperation(controlFlow, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramControlFlowOperation namedElement_controlFlow(final activitydiagram.ControlFlow controlFlow) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramControlFlowOperation(controlFlow, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramControlFlow_AspectOperation controlFlow_Aspect(final activitydiagram.ControlFlow_Aspect controlFlow_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramControlFlow_AspectOperation(controlFlow_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramControlFlow_AspectOperation namedElement_controlFlow_Aspect(final activitydiagram.ControlFlow_Aspect controlFlow_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramControlFlow_AspectOperation(controlFlow_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramControlFlow_AspectOperation controlFlow_controlFlow_Aspect(final activitydiagram.ControlFlow_Aspect controlFlow_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramControlFlow_AspectOperation(controlFlow_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramControlFlow_AspectOperation activityEdge_controlFlow_Aspect(final activitydiagram.ControlFlow_Aspect controlFlow_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramControlFlow_AspectOperation(controlFlow_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramControlFlow_AspectOperation activityEdge_Aspect_controlFlow_Aspect(final activitydiagram.ControlFlow_Aspect controlFlow_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramControlFlow_AspectOperation(controlFlow_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramControlNode_AspectOperation controlNode_Aspect(final activitydiagram.ControlNode_Aspect controlNode_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramControlNode_AspectOperation(controlNode_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramControlNode_AspectOperation controlNode_controlNode_Aspect(final activitydiagram.ControlNode_Aspect controlNode_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramControlNode_AspectOperation(controlNode_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramControlNode_AspectOperation namedElement_controlNode_Aspect(final activitydiagram.ControlNode_Aspect controlNode_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramControlNode_AspectOperation(controlNode_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramControlNode_AspectOperation activityNode_controlNode_Aspect(final activitydiagram.ControlNode_Aspect controlNode_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramControlNode_AspectOperation(controlNode_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramControlNode_AspectOperation activityNode_Aspect_controlNode_Aspect(final activitydiagram.ControlNode_Aspect controlNode_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramControlNode_AspectOperation(controlNode_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramControlTokenOperation controlToken(final activitydiagram.ControlToken controlToken) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramControlTokenOperation(controlToken, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramControlTokenOperation token_controlToken(final activitydiagram.ControlToken controlToken) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramControlTokenOperation(controlToken, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramControlToken_AspectOperation controlToken_Aspect(final activitydiagram.ControlToken_Aspect controlToken_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramControlToken_AspectOperation(controlToken_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramControlToken_AspectOperation token_Aspect_controlToken_Aspect(final activitydiagram.ControlToken_Aspect controlToken_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramControlToken_AspectOperation(controlToken_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramControlToken_AspectOperation controlToken_controlToken_Aspect(final activitydiagram.ControlToken_Aspect controlToken_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramControlToken_AspectOperation(controlToken_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramControlToken_AspectOperation token_controlToken_Aspect(final activitydiagram.ControlToken_Aspect controlToken_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramControlToken_AspectOperation(controlToken_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramDecisionNodeOperation decisionNode(final activitydiagram.DecisionNode decisionNode) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramDecisionNodeOperation(decisionNode, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramDecisionNodeOperation activityNode_decisionNode(final activitydiagram.DecisionNode decisionNode) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramDecisionNodeOperation(decisionNode, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramDecisionNodeOperation controlNode_decisionNode(final activitydiagram.DecisionNode decisionNode) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramDecisionNodeOperation(decisionNode, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramDecisionNodeOperation namedElement_decisionNode(final activitydiagram.DecisionNode decisionNode) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramDecisionNodeOperation(decisionNode, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramDecisionNode_AspectOperation decisionNode_Aspect(final activitydiagram.DecisionNode_Aspect decisionNode_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramDecisionNode_AspectOperation(decisionNode_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramDecisionNode_AspectOperation decisionNode_decisionNode_Aspect(final activitydiagram.DecisionNode_Aspect decisionNode_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramDecisionNode_AspectOperation(decisionNode_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramDecisionNode_AspectOperation controlNode_Aspect_decisionNode_Aspect(final activitydiagram.DecisionNode_Aspect decisionNode_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramDecisionNode_AspectOperation(decisionNode_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramDecisionNode_AspectOperation controlNode_decisionNode_Aspect(final activitydiagram.DecisionNode_Aspect decisionNode_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramDecisionNode_AspectOperation(decisionNode_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramDecisionNode_AspectOperation namedElement_decisionNode_Aspect(final activitydiagram.DecisionNode_Aspect decisionNode_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramDecisionNode_AspectOperation(decisionNode_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramDecisionNode_AspectOperation activityNode_decisionNode_Aspect(final activitydiagram.DecisionNode_Aspect decisionNode_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramDecisionNode_AspectOperation(decisionNode_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramDecisionNode_AspectOperation activityNode_Aspect_decisionNode_Aspect(final activitydiagram.DecisionNode_Aspect decisionNode_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramDecisionNode_AspectOperation(decisionNode_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramExecutableNode_AspectOperation executableNode_Aspect(final activitydiagram.ExecutableNode_Aspect executableNode_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramExecutableNode_AspectOperation(executableNode_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramExecutableNode_AspectOperation namedElement_executableNode_Aspect(final activitydiagram.ExecutableNode_Aspect executableNode_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramExecutableNode_AspectOperation(executableNode_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramExecutableNode_AspectOperation activityNode_executableNode_Aspect(final activitydiagram.ExecutableNode_Aspect executableNode_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramExecutableNode_AspectOperation(executableNode_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramExecutableNode_AspectOperation activityNode_Aspect_executableNode_Aspect(final activitydiagram.ExecutableNode_Aspect executableNode_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramExecutableNode_AspectOperation(executableNode_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramExecutableNode_AspectOperation executableNode_executableNode_Aspect(final activitydiagram.ExecutableNode_Aspect executableNode_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramExecutableNode_AspectOperation(executableNode_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramExpression_AspectOperation expression_Aspect(final activitydiagram.Expression_Aspect expression_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramExpression_AspectOperation(expression_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramExpression_AspectOperation expression_expression_Aspect(final activitydiagram.Expression_Aspect expression_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramExpression_AspectOperation(expression_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramFinalNode_AspectOperation finalNode_Aspect(final activitydiagram.FinalNode_Aspect finalNode_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramFinalNode_AspectOperation(finalNode_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramFinalNode_AspectOperation controlNode_Aspect_finalNode_Aspect(final activitydiagram.FinalNode_Aspect finalNode_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramFinalNode_AspectOperation(finalNode_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramFinalNode_AspectOperation controlNode_finalNode_Aspect(final activitydiagram.FinalNode_Aspect finalNode_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramFinalNode_AspectOperation(finalNode_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramFinalNode_AspectOperation namedElement_finalNode_Aspect(final activitydiagram.FinalNode_Aspect finalNode_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramFinalNode_AspectOperation(finalNode_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramFinalNode_AspectOperation finalNode_finalNode_Aspect(final activitydiagram.FinalNode_Aspect finalNode_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramFinalNode_AspectOperation(finalNode_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramFinalNode_AspectOperation activityNode_finalNode_Aspect(final activitydiagram.FinalNode_Aspect finalNode_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramFinalNode_AspectOperation(finalNode_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramFinalNode_AspectOperation activityNode_Aspect_finalNode_Aspect(final activitydiagram.FinalNode_Aspect finalNode_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramFinalNode_AspectOperation(finalNode_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramForkNodeOperation forkNode(final activitydiagram.ForkNode forkNode) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramForkNodeOperation(forkNode, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramForkNodeOperation activityNode_forkNode(final activitydiagram.ForkNode forkNode) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramForkNodeOperation(forkNode, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramForkNodeOperation controlNode_forkNode(final activitydiagram.ForkNode forkNode) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramForkNodeOperation(forkNode, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramForkNodeOperation namedElement_forkNode(final activitydiagram.ForkNode forkNode) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramForkNodeOperation(forkNode, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramForkNode_AspectOperation forkNode_Aspect(final activitydiagram.ForkNode_Aspect forkNode_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramForkNode_AspectOperation(forkNode_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramForkNode_AspectOperation controlNode_Aspect_forkNode_Aspect(final activitydiagram.ForkNode_Aspect forkNode_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramForkNode_AspectOperation(forkNode_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramForkNode_AspectOperation controlNode_forkNode_Aspect(final activitydiagram.ForkNode_Aspect forkNode_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramForkNode_AspectOperation(forkNode_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramForkNode_AspectOperation namedElement_forkNode_Aspect(final activitydiagram.ForkNode_Aspect forkNode_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramForkNode_AspectOperation(forkNode_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramForkNode_AspectOperation activityNode_forkNode_Aspect(final activitydiagram.ForkNode_Aspect forkNode_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramForkNode_AspectOperation(forkNode_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramForkNode_AspectOperation activityNode_Aspect_forkNode_Aspect(final activitydiagram.ForkNode_Aspect forkNode_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramForkNode_AspectOperation(forkNode_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramForkNode_AspectOperation forkNode_forkNode_Aspect(final activitydiagram.ForkNode_Aspect forkNode_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramForkNode_AspectOperation(forkNode_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramForkedTokenOperation forkedToken(final activitydiagram.ForkedToken forkedToken) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramForkedTokenOperation(forkedToken, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramForkedTokenOperation token_forkedToken(final activitydiagram.ForkedToken forkedToken) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramForkedTokenOperation(forkedToken, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramForkedToken_AspectOperation forkedToken_Aspect(final activitydiagram.ForkedToken_Aspect forkedToken_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramForkedToken_AspectOperation(forkedToken_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramForkedToken_AspectOperation token_Aspect_forkedToken_Aspect(final activitydiagram.ForkedToken_Aspect forkedToken_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramForkedToken_AspectOperation(forkedToken_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramForkedToken_AspectOperation forkedToken_forkedToken_Aspect(final activitydiagram.ForkedToken_Aspect forkedToken_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramForkedToken_AspectOperation(forkedToken_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramForkedToken_AspectOperation token_forkedToken_Aspect(final activitydiagram.ForkedToken_Aspect forkedToken_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramForkedToken_AspectOperation(forkedToken_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramInitialNodeOperation initialNode(final activitydiagram.InitialNode initialNode) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramInitialNodeOperation(initialNode, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramInitialNodeOperation activityNode_initialNode(final activitydiagram.InitialNode initialNode) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramInitialNodeOperation(initialNode, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramInitialNodeOperation controlNode_initialNode(final activitydiagram.InitialNode initialNode) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramInitialNodeOperation(initialNode, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramInitialNodeOperation namedElement_initialNode(final activitydiagram.InitialNode initialNode) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramInitialNodeOperation(initialNode, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramInitialNode_AspectOperation initialNode_Aspect(final activitydiagram.InitialNode_Aspect initialNode_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramInitialNode_AspectOperation(initialNode_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramInitialNode_AspectOperation controlNode_Aspect_initialNode_Aspect(final activitydiagram.InitialNode_Aspect initialNode_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramInitialNode_AspectOperation(initialNode_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramInitialNode_AspectOperation controlNode_initialNode_Aspect(final activitydiagram.InitialNode_Aspect initialNode_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramInitialNode_AspectOperation(initialNode_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramInitialNode_AspectOperation namedElement_initialNode_Aspect(final activitydiagram.InitialNode_Aspect initialNode_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramInitialNode_AspectOperation(initialNode_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramInitialNode_AspectOperation initialNode_initialNode_Aspect(final activitydiagram.InitialNode_Aspect initialNode_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramInitialNode_AspectOperation(initialNode_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramInitialNode_AspectOperation activityNode_initialNode_Aspect(final activitydiagram.InitialNode_Aspect initialNode_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramInitialNode_AspectOperation(initialNode_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramInitialNode_AspectOperation activityNode_Aspect_initialNode_Aspect(final activitydiagram.InitialNode_Aspect initialNode_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramInitialNode_AspectOperation(initialNode_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramInputOperation input(final activitydiagram.Input input) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramInputOperation(input, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramInputOperation input(final activitydiagram.Input input) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramInputOperation(input, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramInputOperation input_input(final activitydiagram.Input input) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramInputOperation(input, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramInputValueOperation inputValue(final activitydiagram.InputValue inputValue) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramInputValueOperation(inputValue, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramInputValueOperation inputValue_inputValue(final activitydiagram.InputValue inputValue) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramInputValueOperation(inputValue, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramInputValueOperation inputValue(final activitydiagram.InputValue inputValue) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramInputValueOperation(inputValue, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramIntegerCalculationExpressionOperation integerCalculationExpression(final activitydiagram.IntegerCalculationExpression integerCalculationExpression) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramIntegerCalculationExpressionOperation(integerCalculationExpression, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramIntegerCalculationExpressionOperation integerExpression_integerCalculationExpression(final activitydiagram.IntegerCalculationExpression integerCalculationExpression) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramIntegerCalculationExpressionOperation(integerCalculationExpression, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramIntegerCalculationExpressionOperation expression_integerCalculationExpression(final activitydiagram.IntegerCalculationExpression integerCalculationExpression) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramIntegerCalculationExpressionOperation(integerCalculationExpression, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramIntegerCalculationExpression_AspectOperation integerCalculationExpression_Aspect(final activitydiagram.IntegerCalculationExpression_Aspect integerCalculationExpression_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramIntegerCalculationExpression_AspectOperation(integerCalculationExpression_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramIntegerCalculationExpression_AspectOperation expression_Aspect_integerCalculationExpression_Aspect(final activitydiagram.IntegerCalculationExpression_Aspect integerCalculationExpression_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramIntegerCalculationExpression_AspectOperation(integerCalculationExpression_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramIntegerCalculationExpression_AspectOperation integerExpression_integerCalculationExpression_Aspect(final activitydiagram.IntegerCalculationExpression_Aspect integerCalculationExpression_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramIntegerCalculationExpression_AspectOperation(integerCalculationExpression_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramIntegerCalculationExpression_AspectOperation integerExpression_Aspect_integerCalculationExpression_Aspect(final activitydiagram.IntegerCalculationExpression_Aspect integerCalculationExpression_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramIntegerCalculationExpression_AspectOperation(integerCalculationExpression_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramIntegerCalculationExpression_AspectOperation integerCalculationExpression_integerCalculationExpression_Aspect(final activitydiagram.IntegerCalculationExpression_Aspect integerCalculationExpression_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramIntegerCalculationExpression_AspectOperation(integerCalculationExpression_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramIntegerCalculationExpression_AspectOperation expression_integerCalculationExpression_Aspect(final activitydiagram.IntegerCalculationExpression_Aspect integerCalculationExpression_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramIntegerCalculationExpression_AspectOperation(integerCalculationExpression_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramIntegerComparisonExpressionOperation integerComparisonExpression(final activitydiagram.IntegerComparisonExpression integerComparisonExpression) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramIntegerComparisonExpressionOperation(integerComparisonExpression, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramIntegerComparisonExpressionOperation integerExpression_integerComparisonExpression(final activitydiagram.IntegerComparisonExpression integerComparisonExpression) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramIntegerComparisonExpressionOperation(integerComparisonExpression, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramIntegerComparisonExpressionOperation expression_integerComparisonExpression(final activitydiagram.IntegerComparisonExpression integerComparisonExpression) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramIntegerComparisonExpressionOperation(integerComparisonExpression, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramIntegerComparisonExpression_AspectOperation integerComparisonExpression_Aspect(final activitydiagram.IntegerComparisonExpression_Aspect integerComparisonExpression_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramIntegerComparisonExpression_AspectOperation(integerComparisonExpression_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramIntegerComparisonExpression_AspectOperation expression_Aspect_integerComparisonExpression_Aspect(final activitydiagram.IntegerComparisonExpression_Aspect integerComparisonExpression_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramIntegerComparisonExpression_AspectOperation(integerComparisonExpression_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramIntegerComparisonExpression_AspectOperation integerExpression_integerComparisonExpression_Aspect(final activitydiagram.IntegerComparisonExpression_Aspect integerComparisonExpression_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramIntegerComparisonExpression_AspectOperation(integerComparisonExpression_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramIntegerComparisonExpression_AspectOperation integerExpression_Aspect_integerComparisonExpression_Aspect(final activitydiagram.IntegerComparisonExpression_Aspect integerComparisonExpression_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramIntegerComparisonExpression_AspectOperation(integerComparisonExpression_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramIntegerComparisonExpression_AspectOperation expression_integerComparisonExpression_Aspect(final activitydiagram.IntegerComparisonExpression_Aspect integerComparisonExpression_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramIntegerComparisonExpression_AspectOperation(integerComparisonExpression_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramIntegerComparisonExpression_AspectOperation integerComparisonExpression_integerComparisonExpression_Aspect(final activitydiagram.IntegerComparisonExpression_Aspect integerComparisonExpression_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramIntegerComparisonExpression_AspectOperation(integerComparisonExpression_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramIntegerExpression_AspectOperation integerExpression_Aspect(final activitydiagram.IntegerExpression_Aspect integerExpression_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramIntegerExpression_AspectOperation(integerExpression_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramIntegerExpression_AspectOperation expression_Aspect_integerExpression_Aspect(final activitydiagram.IntegerExpression_Aspect integerExpression_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramIntegerExpression_AspectOperation(integerExpression_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramIntegerExpression_AspectOperation integerExpression_integerExpression_Aspect(final activitydiagram.IntegerExpression_Aspect integerExpression_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramIntegerExpression_AspectOperation(integerExpression_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramIntegerExpression_AspectOperation expression_integerExpression_Aspect(final activitydiagram.IntegerExpression_Aspect integerExpression_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramIntegerExpression_AspectOperation(integerExpression_Aspect, this);
	} 
	@Override
	default activitydiagram.$default.algebra.operation.Activitydiagram$defaultIntegerValueOperation integerValue(final activitydiagram.IntegerValue integerValue) {
		return new activitydiagram.$default.algebra.impl.operation.Activitydiagram$defaultIntegerValueOperation(integerValue, this);
	} 
	@Override
	default activitydiagram.$default.algebra.operation.Activitydiagram$defaultIntegerValueOperation value_integerValue(final activitydiagram.IntegerValue integerValue) {
		return new activitydiagram.$default.algebra.impl.operation.Activitydiagram$defaultIntegerValueOperation(integerValue, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramIntegerVariableOperation integerVariable(final activitydiagram.IntegerVariable integerVariable) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramIntegerVariableOperation(integerVariable, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramIntegerVariableOperation variable_integerVariable(final activitydiagram.IntegerVariable integerVariable) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramIntegerVariableOperation(integerVariable, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramIntegerVariable_AspectOperation integerVariable_Aspect(final activitydiagram.IntegerVariable_Aspect integerVariable_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramIntegerVariable_AspectOperation(integerVariable_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramIntegerVariable_AspectOperation integerVariable_integerVariable_Aspect(final activitydiagram.IntegerVariable_Aspect integerVariable_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramIntegerVariable_AspectOperation(integerVariable_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramIntegerVariable_AspectOperation variable_Aspect_integerVariable_Aspect(final activitydiagram.IntegerVariable_Aspect integerVariable_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramIntegerVariable_AspectOperation(integerVariable_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramIntegerVariable_AspectOperation variable_integerVariable_Aspect(final activitydiagram.IntegerVariable_Aspect integerVariable_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramIntegerVariable_AspectOperation(integerVariable_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramJoinNodeOperation joinNode(final activitydiagram.JoinNode joinNode) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramJoinNodeOperation(joinNode, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramJoinNodeOperation activityNode_joinNode(final activitydiagram.JoinNode joinNode) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramJoinNodeOperation(joinNode, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramJoinNodeOperation controlNode_joinNode(final activitydiagram.JoinNode joinNode) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramJoinNodeOperation(joinNode, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramJoinNodeOperation namedElement_joinNode(final activitydiagram.JoinNode joinNode) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramJoinNodeOperation(joinNode, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramJoinNode_AspectOperation joinNode_Aspect(final activitydiagram.JoinNode_Aspect joinNode_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramJoinNode_AspectOperation(joinNode_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramJoinNode_AspectOperation controlNode_Aspect_joinNode_Aspect(final activitydiagram.JoinNode_Aspect joinNode_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramJoinNode_AspectOperation(joinNode_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramJoinNode_AspectOperation controlNode_joinNode_Aspect(final activitydiagram.JoinNode_Aspect joinNode_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramJoinNode_AspectOperation(joinNode_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramJoinNode_AspectOperation namedElement_joinNode_Aspect(final activitydiagram.JoinNode_Aspect joinNode_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramJoinNode_AspectOperation(joinNode_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramJoinNode_AspectOperation joinNode_joinNode_Aspect(final activitydiagram.JoinNode_Aspect joinNode_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramJoinNode_AspectOperation(joinNode_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramJoinNode_AspectOperation activityNode_joinNode_Aspect(final activitydiagram.JoinNode_Aspect joinNode_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramJoinNode_AspectOperation(joinNode_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramJoinNode_AspectOperation activityNode_Aspect_joinNode_Aspect(final activitydiagram.JoinNode_Aspect joinNode_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramJoinNode_AspectOperation(joinNode_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramMergeNodeOperation mergeNode(final activitydiagram.MergeNode mergeNode) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramMergeNodeOperation(mergeNode, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramMergeNodeOperation activityNode_mergeNode(final activitydiagram.MergeNode mergeNode) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramMergeNodeOperation(mergeNode, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramMergeNodeOperation controlNode_mergeNode(final activitydiagram.MergeNode mergeNode) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramMergeNodeOperation(mergeNode, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramMergeNodeOperation namedElement_mergeNode(final activitydiagram.MergeNode mergeNode) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramMergeNodeOperation(mergeNode, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramMergeNode_AspectOperation mergeNode_Aspect(final activitydiagram.MergeNode_Aspect mergeNode_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramMergeNode_AspectOperation(mergeNode_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramMergeNode_AspectOperation controlNode_Aspect_mergeNode_Aspect(final activitydiagram.MergeNode_Aspect mergeNode_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramMergeNode_AspectOperation(mergeNode_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramMergeNode_AspectOperation controlNode_mergeNode_Aspect(final activitydiagram.MergeNode_Aspect mergeNode_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramMergeNode_AspectOperation(mergeNode_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramMergeNode_AspectOperation namedElement_mergeNode_Aspect(final activitydiagram.MergeNode_Aspect mergeNode_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramMergeNode_AspectOperation(mergeNode_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramMergeNode_AspectOperation activityNode_mergeNode_Aspect(final activitydiagram.MergeNode_Aspect mergeNode_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramMergeNode_AspectOperation(mergeNode_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramMergeNode_AspectOperation activityNode_Aspect_mergeNode_Aspect(final activitydiagram.MergeNode_Aspect mergeNode_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramMergeNode_AspectOperation(mergeNode_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramMergeNode_AspectOperation mergeNode_mergeNode_Aspect(final activitydiagram.MergeNode_Aspect mergeNode_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramMergeNode_AspectOperation(mergeNode_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramOfferOperation offer(final activitydiagram.Offer offer) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramOfferOperation(offer, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramOffer_AspectOperation offer_Aspect(final activitydiagram.Offer_Aspect offer_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramOffer_AspectOperation(offer_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramOffer_AspectOperation offer_offer_Aspect(final activitydiagram.Offer_Aspect offer_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramOffer_AspectOperation(offer_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramOpaqueActionOperation opaqueAction(final activitydiagram.OpaqueAction opaqueAction) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramOpaqueActionOperation(opaqueAction, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramOpaqueActionOperation namedElement_opaqueAction(final activitydiagram.OpaqueAction opaqueAction) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramOpaqueActionOperation(opaqueAction, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramOpaqueActionOperation activityNode_opaqueAction(final activitydiagram.OpaqueAction opaqueAction) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramOpaqueActionOperation(opaqueAction, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramOpaqueActionOperation action_opaqueAction(final activitydiagram.OpaqueAction opaqueAction) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramOpaqueActionOperation(opaqueAction, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramOpaqueActionOperation executableNode_opaqueAction(final activitydiagram.OpaqueAction opaqueAction) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramOpaqueActionOperation(opaqueAction, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramOpaqueAction_AspectOperation opaqueAction_Aspect(final activitydiagram.OpaqueAction_Aspect opaqueAction_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramOpaqueAction_AspectOperation(opaqueAction_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramOpaqueAction_AspectOperation namedElement_opaqueAction_Aspect(final activitydiagram.OpaqueAction_Aspect opaqueAction_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramOpaqueAction_AspectOperation(opaqueAction_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramOpaqueAction_AspectOperation activityNode_opaqueAction_Aspect(final activitydiagram.OpaqueAction_Aspect opaqueAction_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramOpaqueAction_AspectOperation(opaqueAction_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramOpaqueAction_AspectOperation executableNode_Aspect_opaqueAction_Aspect(final activitydiagram.OpaqueAction_Aspect opaqueAction_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramOpaqueAction_AspectOperation(opaqueAction_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramOpaqueAction_AspectOperation action_opaqueAction_Aspect(final activitydiagram.OpaqueAction_Aspect opaqueAction_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramOpaqueAction_AspectOperation(opaqueAction_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramOpaqueAction_AspectOperation executableNode_opaqueAction_Aspect(final activitydiagram.OpaqueAction_Aspect opaqueAction_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramOpaqueAction_AspectOperation(opaqueAction_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramOpaqueAction_AspectOperation opaqueAction_opaqueAction_Aspect(final activitydiagram.OpaqueAction_Aspect opaqueAction_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramOpaqueAction_AspectOperation(opaqueAction_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramOpaqueAction_AspectOperation action_Aspect_opaqueAction_Aspect(final activitydiagram.OpaqueAction_Aspect opaqueAction_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramOpaqueAction_AspectOperation(opaqueAction_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramOpaqueAction_AspectOperation activityNode_Aspect_opaqueAction_Aspect(final activitydiagram.OpaqueAction_Aspect opaqueAction_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramOpaqueAction_AspectOperation(opaqueAction_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramToken_AspectOperation token_Aspect(final activitydiagram.Token_Aspect token_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramToken_AspectOperation(token_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramToken_AspectOperation token_token_Aspect(final activitydiagram.Token_Aspect token_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramToken_AspectOperation(token_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramTraceOperation trace(final activitydiagram.Trace trace) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramTraceOperation(trace, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramTrace_AspectOperation trace_Aspect(final activitydiagram.Trace_Aspect trace_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramTrace_AspectOperation(trace_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramTrace_AspectOperation trace_trace_Aspect(final activitydiagram.Trace_Aspect trace_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramTrace_AspectOperation(trace_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramVariable_AspectOperation variable_Aspect(final activitydiagram.Variable_Aspect variable_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramVariable_AspectOperation(variable_Aspect, this);
	} 
	@Override
	default activitydiagram.activitydiagram.algebra.operation.ActivitydiagramActivitydiagramVariable_AspectOperation variable_variable_Aspect(final activitydiagram.Variable_Aspect variable_Aspect) {
		return new activitydiagram.activitydiagram.algebra.impl.operation.ActivitydiagramActivitydiagramVariable_AspectOperation(variable_Aspect, this);
	} 
}
